spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/habitflow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: habitflow
    password: habitflow
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5s
  cache:
    type: ${SPRING_CACHE_TYPE:simple}

mybatis-plus:
  type-aliases-package: com.habitflow.backend.domain.entity
  configuration:
    map-underscore-to-camel-case: true
